# ----------------- BEGIN MIX-IN DEFINITIONS -----------------
# Mix-In definitions are auto-generated by mixin-update
##############################################################
# Source: device/intel/mixins/groups/boot-arch/project-celadon/unlock_device.nsh
##############################################################
dmpstore OEMLock -l efivar_oemlock
# ------------------ END MIX-IN DEFINITIONS ------------------
