[extrafiles]
media_codecs_c2.xml: "Specific configuration for audio and video codec2.0"
media_codecs_goldfish_c2_video.xml: "Specific configuration for Goldfish c2 codecs"
media_codecs_performance_c2.xml: "Media codec2.0 performance file for Goldfish c2 codecs"
codec2.vendor.ext.policy: "Goldfish c2 policy"
android.hardware.media.c2@1.0-service-goldfish: "Media c2 service"
libgoldfish_codec2_store_32.so: "Media c2 store"
libcodec2_goldfish_common_32.so: "Media c2 common"
libcodec2_goldfish_avcdec_32.so: "Media c2 h264 32"
libcodec2_goldfish_vp8dec_32.so: "Media c2 vp8 decoder 32"
libcodec2_goldfish_vp9dec_32.so: "Media c2 vp9 decoder 32"
libcodec2_goldfish_hevcdec_32.so: "Media c2 h265 decoder 32"
libgoldfish_codec2_store_64.so: "Media c2 store 64"
libcodec2_goldfish_common_64.so: "Media c2 common 64"
libcodec2_goldfish_avcdec_64.so: "Media c2 h264 64"
libcodec2_goldfish_vp8dec_64.so: "Media c2 vp8 decoder 64"
libcodec2_goldfish_vp9dec_64.so: "Media c2 vp9 decoder 64"
libcodec2_goldfish_hevcdec_64.so: "Media c2 h265 decoder 64"
android.hardware.media.c2@1.0-service-goldfish.rc: "Media init"