#!/usr/bin/env python

import os
import uuid
import sys

FAKE_MIXIN_OUTPUTS = [
    "device/intel/broxton/mixin-fake-output",
    "device/intel/cherrytrail/mixin-fake-output",]


def _findRepoRoot():
    curdir = os.getcwd()
    while curdir != os.path.dirname(curdir):
        repo_dir = os.path.join(curdir, ".repo")
        if os.path.isdir(repo_dir):
            return os.path.dirname(repo_dir)  # path to .repo
        curdir = os.path.dirname(curdir)
    raise IOError("current directory is not in a repo environment")


def main():
    repo_dir = _findRepoRoot()
    for filename in FAKE_MIXIN_OUTPUTS:
        output = os.path.join(repo_dir, filename)
        print "Creating fake mixin-update output: {}".format(output)
        with open(output, 'w') as fp:
            fp.write(uuid.uuid4().hex)


if __name__ == '__main__':
    ret = main()
    sys.exit(ret)
