[extrafiles]
media_codecs_performance_c2_tgl.xml: "Media codec2.0 performance file for tigerlake"
media_codecs_performance_c2_adl.xml: "Media codec2.0 performance file for alderlake"
mfx_c2_store.conf: "MSDK configuration for video codec2.0"
mfx_c2_store_mtl.conf: "MSDK video codec2.0 configuration for meteorlake"
media_codecs.xml: "Specific configuration for audio and video codec2.0"
media_codecs_gen9.xml: "Specific codec2.0 configuration for Intel gen9"
media_codecs_gen12.xml: "Specific codec2.0 configuration for Intel gen12"
media_codecs_mtl.xml: "Specific codec2.0 configuration for Intel meteorlake"
media_codecs_intel_c2_video.xml: "Specific configuration for intel video codec2.0"
media_codecs_intel_c2_video_mtl.xml: "Specific intel video codec2.0 configuration for meteorlake"
