root = "/data/vendor/docker/var/lib/containerd"
state = "/data/vendor/docker/run/containerd"
imports = ["/data/vendor/docker/etc/containerd/runtime_*.toml", "./debug.toml"]

[grpc]
  address = "/data/vendor/docker/run/containerd/containerd.sock"

[debug]
  address = "/data/vendor/docker/run/containerd/debug.sock"

[plugins]
  [plugins.opt]
    path = "/data/vendor/docker/opt"
  [plugins.cri.cni]
    bin_dir = "/data/vendor/docker/opt/cni/bin"
    conf_dir = "/data/vendor/docker/etc/cni/net.d"
