#! /bin/sh
# Checks for Android Screen On or Off
if adb get-state 1>/dev/null 2>&1
then
	state=$(adb shell dumpsys display | grep mScreenState= | grep -oE '(ON|OFF)')

	if [ "$state" = "ON" ]; then
		exit 254
	else
		exit 0
	fi
else
	exit 0
fi
