OPTEE_PLATFORM ?= kbl
OPTEE_PLATFORM_FLAVOR ?= ivshmem
OPTEE_ARCH ?= x86_64
OPTEE_TA_TARGETS ?= ta_x86_64
OPTEE_OS_DIR ?= vendor/intel/optee/optee_os
OPTEE_EXTRA_FLAGS ?= ARCH=x86_64 COMPILER=clang OPTEE_CLANG_COMPILER_PATH=$(CLANG_PREBUILTS_PATH)/host/$(HOST_OS)-x86/$(KERNEL_CLANG_VERSION)/bin/ CFG_TEE_CORE_LOG_LEVEL=3 CFG_TEE_TA_LOG_LEVEL=3 DEBUG=1 CFG_TEE_BENCHMARK=n
CROSS_COMPILE32 ?= x86_64-unknown-linux-gnu-
CROSS_COMPILE64 ?= x86_64-unknown-linux-gnu-
OPTEE_EXTRA_TA_FLAGS ?= $(OPTEE_EXTRA_FLAGS)
BUILD_OPTEE_MK := $(OPTEE_OS_DIR)/mk/aosp_optee.mk

BOARD_SEPOLICY_DIRS += $(INTEL_PATH_SEPOLICY)/optee/enabled
