[extrafiles]
media_codecs_gen9.xml: "Specific configuration for audio and video codecs for gen9"
media_codecs_gen11.xml: "Specific configuration for audio and video codecs for gen11"
media_codecs_gen12.xml: "Specific configuration for audio and video codecs for gen12"
mfx_omxil_core.conf: "MSDK configuration for video codecs"
media_profiles.xml: "Media profile file"
media_profiles_1080p.xml: "Media profile file with 1080p support"
media_codecs_performance_cml.xml: "Media codecs performance file for cml"
media_codecs_performance_ehl.xml: "Media codecs performance file for ehl"
media_codecs_performance_tgl.xml: "Media codecs performance file for tgl"
media_codecs_performance_{{platform}}_xen.xml: "Media codecs performance file for xen"
media_codecs_vp9.xml: "vp9 support"
mfx_omxil_core_vp9.conf: "vp9 support"
auto_hal.in: "auto script to detect platform and set property"
