BOARD_EGL_CFG := $(INTEL_PATH_COMMON)/graphics/mali/egl.cfg
USE_OPENGL_RENDERER := true
TARGET_DISABLE_TRIPLE_BUFFERING := false
SF_VSYNC_EVENT_PHASE_OFFSET_NS := 5000000
VSYNC_EVENT_PHASE_OFFSET_NS := 7500000
BOARD_GRAPHIC_IS_MALI := true
BOARD_SEPOLICY_DIRS += $(INTEL_PATH_SEPOLICY)/graphics/mali-common
