#!/usr/bin/env bash
# author: sundar.gnanasekaran@intel.com


export AIC_WORK_DIR=/opt/cic
cuser=`echo $HOME | cut -d'/' -f3`

## Set default values
if [[ -z $SECURE ]]; then
  SECURE="false"
fi

if [[ -z $MULTIPLE_USER ]]; then
  MULTIPLE_USER="false"
fi

if [[ -z $AUDIO_MT && -z $AUDIO_PT ]]; then
  AUDIO_MT="true"
  AUDIO_PT="false"
fi

if [[ -z $WIFI_MT && -z $WIFI_PT ]]; then
  WIFI_MT="true"
  WIFI_PT="false"
fi

if [[ -z $BT_MT && -z $BT_PT ]]; then
  BT_MT="true"
  BT_PT="false"
fi


## Create setup-aic arguments
SETUP_AIC_ARGS=""
PASSTHROUGH=""

if [[ $SECURE == "true" ]]; then
  SETUP_AIC_ARGS="$SETUP_AIC_ARGS -s"
fi

if [[ $MULTIPLE_USER == "true" ]]; then
  SETUP_AIC_ARGS="$SETUP_AIC_ARGS -j"
fi

if [[ $AUDIO_PT == "true" ]]; then
  PASSTHROUGH="audio,$PASSTHROUGH"
fi

if [[ $BT_PT == "true" ]]; then
  PASSTHROUGH="bt,$PASSTHROUGH"
fi

if [[ $WIFI_PT == "true" ]]; then
  PASSTHROUGH="wifi,$PASSTHROUGH"
fi

if [[ ! -z $PASSTHROUGH ]]; then
  PASSTHROUGH=`echo $PASSTHROUGH | sed 's/.$//'`
  SETUP_AIC_ARGS="$SETUP_AIC_ARGS -p $PASSTHROUGH"
fi


## Start setup-aic
echo "*********************************************"
echo "Executing setup-aic"
echo "Command : ./setup-aic $SETUP_AIC_ARGS"
echo "*********************************************"
export DEBIAN=true
cd $AIC_WORK_DIR && ./setup-aic $SETUP_AIC_ARGS
