#!/usr/bin/env bash
# author: sundar.gnanasekaran@intel.com

export AIC_WORK_DIR=${PWD}

#customize android (add/remove apps etc.)
./pre-requisites/customize-android

#Check env path
AIC_WORK_DIR_PATH=$AIC_WORK_DIR/workdir
a=`grep -rn AIC_WORK_DIR /etc/environment`
if [ -z "$a" ]; then
	echo "export AIC_WORK_DIR=$AIC_WORK_DIR_PATH" | sudo tee -a /etc/environment
else
	sudo sed -i "s|export AIC_WORK_DIR.*||g" /etc/environment
	echo "export AIC_WORK_DIR=$AIC_WORK_DIR_PATH" | sudo tee -a /etc/environment
fi

a=`grep -rn AIC_WORK_DIR $HOME/.bashrc`
if [ -z "$a" ]; then
	echo "export AIC_WORK_DIR=$AIC_WORK_DIR_PATH" | sudo tee -a $HOME/.bashrc
else
	sudo sed -i "s|export AIC_WORK_DIR.*||g" $HOME/.bashrc
	echo "export AIC_WORK_DIR=$AIC_WORK_DIR_PATH" | sudo tee -a $HOME/.bashrc
fi

## Identify & set device serial ID
serial=`sudo cat /sys/devices/virtual/dmi/id/board_serial`
if [[ ! -f $AIC_WORK_DIR_PATH/data0/local.prop ]]; then
  mkdir -p $AIC_WORK_DIR_PATH/data0
  cd $AIC_WORK_DIR_PATH/data0 && touch local.prop
  cd $AIC_WORK_DIR
fi

if [[ -z `grep "ro.serialno" $AIC_WORK_DIR_PATH/data0/local.prop` ]]; then
  echo "ro.serialno=$serial" >> $AIC_WORK_DIR_PATH/data0/local.prop
fi

#set Time zone property
localtz=$(timedatectl status |grep "Time zone")
localtzarr=(${localtz// / })
shorttz=${localtzarr[2]}
if [[ -z `grep "persist.sys.timezone" $AIC_WORK_DIR_PATH/data0/local.prop` ]]; then
  echo "persist.sys.timezone=$shorttz" >> $AIC_WORK_DIR_PATH/data0/local.prop
fi

sudo chmod 777 -R $AIC_WORK_DIR_PATH
sudo chmod 0644 $AIC_WORK_DIR_PATH/data0/local.prop

#Run pactl
./pre-requisites/pactl_socket $(whoami)
