#!/usr/bin/env bash
# author: sundar.gnanasekaran@intel.com

#Host Setup
./setup-host $@

#Install Feature set packages / modules
./pre-requisites/setup-feature

#Initiate Early-Launch
#./pre-requisites/launch-early
./pre-requisites/cic-service

#Install CIC
cd $AIC_WORK_DIR
echo "Installing CIC -- START"
./aic install -u -e -d none
echo "Installing CIC -- DONE"

sudo systemctl enable cic

echo ""
echo "Reboot required for changes to be reflected !!"
read -p "Press Enter key to reboot: "
sudo reboot
