#!/usr/bin/env bash
# author: sundar.gnanasekaran@intel.com

security=$1

## Check trusty status
teedata=`sudo parted -l | grep -i teedata`
trusty_host=`dmesg | grep trusty`
tos_img=`dmesg | grep trusty | grep 'error -22'`
trusty_init=`dmesg | grep trusty | grep 'initializ'`


### If trusty is enabled

## Check if /teedata is present
if [[ -z $teedata && $security == "true" ]]; then
    echo "Partition /teedata not present"
    echo "Please create one"
    exit -1
fi

## check if trusty drivers are enabled
if [[ $trusty_host == "" && $security == "true" ]]; then
    echo "Trusty not enabled in kernel"
    echo "Please install trusty drivers in host kernel"
    echo "security : $security"
fi

## copy KF and tos to ubuntu
if [[ $security == "true" ]]; then
    echo "Copying trusty"
    sudo cp $AIC_WORK_DIR/tos.img /boot/efi/EFI/ubuntu/.

    a=`sudo grep -irnsH 'microsoft corporation' /boot/efi/EFI/ubuntu/shimx64.efi`
    b=`sudo grep -irnsH 'android@android' /boot/efi/EFI/ubuntu/shimx64.efi`
    c=`sudo grep -irnsH 'microsoft corporation' /boot/efi/EFI/ubuntu/loaderx64.efi`
    if [[ ! -z $a ]]; then
        sudo cp /boot/efi/EFI/ubuntu/shimx64.efi /boot/efi/EFI/ubuntu/loaderx64.efi
        sudo cp $AIC_WORK_DIR/kf4cic.efi /boot/efi/EFI/ubuntu/shimx64.efi
    fi
    if [[ ! -z $b && ! -z $c ]]; then
        sudo cp $AIC_WORK_DIR/kf4cic.efi /boot/efi/EFI/ubuntu/shimx64.efi
    fi
fi

### If trusty is disabled

if [[ $security == "" || $security == "false" ]]; then

## Remove trusty from android
echo '
#Disable trusty
sed -i 's/trusty//g' /system/build.prop
rm -rf /vendor/lib/hw/gatekeeper.trusty.so
rm -rf /vendor/lib/hw/keystore.trusty.so
rm -rf /vendor/lib/libtrusty.so
rm -rf /vendor/lib64/hw/gatekeeper.trusty.so
rm -rf /vendor/lib64/hw/keystore.trusty.so
rm -rf /vendor/lib64/libtrusty.so
rm -rf /vendor/etc/init/android.hardware.gatekeeper@1.0-service.rc
rm -rf /vendor/lib/hw/gatekeeper.trusty.so
rm -rf /vendor/lib/hw/android.hardware.gatekeeper@1.0-impl.so
rm -rf /vendor/lib64/hw/gatekeeper.trusty.so
rm -rf /vendor/lib64/hw/android.hardware.gatekeeper@1.0-impl.so
rm -rf /vendor/bin/hw/android.hardware.gatekeeper@1.0-service

' >> $AIC_WORK_DIR/update/customize-android

    ## Remove KF and tos from ubuntu
    sudo rm -rf /boot/efi/EFI/ubuntu/tos.img

    a=`sudo grep -irnsH 'microsoft corporation' /boot/efi/EFI/ubuntu/shimx64.efi`
    b=`sudo grep -irnsH 'android@android' /boot/efi/EFI/ubuntu/shimx64.efi`
    c=`sudo grep -irnsH 'microsoft corporation' /boot/efi/EFI/ubuntu/loaderx64.efi`
    if [[ (-z $a) && ! (-z $c) ]]; then
        sudo mv /boot/efi/EFI/ubuntu/loaderx64.efi /boot/efi/EFI/ubuntu/shimx64.efi
    fi
fi
