INTEL_STAGEFRIGHT := true
USE_MEDIASDK := true
BOARD_HAVE_MEDIASDK_OPEN_SOURCE := true
ENABLE_MAX_NUM_REORDER_FRAMES_OUTPUT := false
BOARD_HAVE_OMX_SRC := true

# OneVPL integration
USE_ONEVPL := true

