OPTEE_PLATFORM ?= standalonevm
OPTEE_PLATFORM_FLAVOR ?= ivi
OPTEE_ARCH ?= x86_64
OPTEE_TA_TARGETS ?= ta_x86_64
OPTEE_OS_DIR ?= vendor/intel/optee/optee_os
ifeq ($(TARGET_BUILD_VARIANT),user)
OPTEE_EXTRA_FLAGS ?= ARCH=x86_64 COMPILER=clang OPTEE_CLANG_COMPILER_PATH=$(CLANG_PREBUILTS_PATH)/host/$(HOST_OS)-x86/$(KERNEL_CLANG_VERSION)/bin/ CFG_TEE_CORE_LOG_LEVEL=1 CFG_TEE_TA_LOG_LEVEL=1 DEBUG=0 CFG_TEE_CORE_DEBUG=n CFG_TEE_BENCHMARK=n
else
OPTEE_EXTRA_FLAGS ?= ARCH=x86_64 COMPILER=clang OPTEE_CLANG_COMPILER_PATH=$(CLANG_PREBUILTS_PATH)/host/$(HOST_OS)-x86/$(KERNEL_CLANG_VERSION)/bin/ CFG_TEE_CORE_LOG_LEVEL=3 CFG_TEE_TA_LOG_LEVEL=3 DEBUG=1 CFG_TEE_BENCHMARK=n
endif
CROSS_COMPILE32 ?= x86_64-unknown-linux-gnu-
CROSS_COMPILE64 ?= x86_64-unknown-linux-gnu-
OPTEE_EXTRA_TA_FLAGS ?= $(OPTEE_EXTRA_FLAGS)
BUILD_OPTEE_MK := $(OPTEE_OS_DIR)/mk/aosp_optee.mk

TARGET_USE_OPTEE := true
TARGET_USE_IVSHMEM := true
BOARD_SEPOLICY_DIRS += $(INTEL_PATH_SEPOLICY)/tee/optee

AB_OTA_PARTITIONS += tee

include vendor/intel/optee/optee_client/optee_client.device.mk
$(call soong_config_set,optee_client,cfg_tee_fs_parent_path,/persist/tee)
